name: Build Workflow 1
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print Success
        run: echo "Success in Build Workflow 1"
