name: Build Workflow 2
on:
  push:
    branches:
      - feature

jobs:
  build:
    name: Build Job 2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print Success
        run: echo "Success in Build Workflow 2"
